blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/your-username/chrome-extractor/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/your-username/chrome-extractor/wiki
    about: Check our documentation and guides
